CREATE TABLE IF NOT EXISTS `#__fgreports_reports` (
    `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(255) NOT NULL DEFAULT '',
    `alias` VARCHAR(255) NOT NULL DEFAULT '',
    `description` TEXT NULL,
    `sql_script` MEDIUMTEXT NOT NULL,
    `cache_ttl` INT(11) NOT NULL DEFAULT 0,
    `page_limit` INT(11) NOT NULL DEFAULT 0,
    `stack_mobile` TINYINT(1) NOT NULL DEFAULT 1,
    `table_css_class` VARCHAR(255) NOT NULL DEFAULT '',
    `enable_sorting` TINYINT(1) NOT NULL DEFAULT 1,
    `access` INT(11) UNSIGNED NOT NULL DEFAULT 1,
    `published` TINYINT(3) NOT NULL DEFAULT 0,
    `ordering` INT(11) NOT NULL DEFAULT 0,
    `params` TEXT NULL COMMENT 'Reserved for future report parameters/filters',
    `created` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00',
    `created_by` INT(11) UNSIGNED NOT NULL DEFAULT 0,
    `modified` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00',
    `modified_by` INT(11) UNSIGNED NOT NULL DEFAULT 0,
    `checked_out` INT(11) UNSIGNED NOT NULL DEFAULT 0,
    `checked_out_time` DATETIME NULL,
    PRIMARY KEY (`id`),
    KEY `idx_alias` (`alias`),
    KEY `idx_published` (`published`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
